#!/usr/bin/env python3
"""
Test Suite for WhatsApp Watcher
Tests core functionality without requiring live WhatsApp connection

Version: 1.0
Status: Ready for Testing
Created: 2026-02-22
"""

import unittest
import tempfile
import shutil
from pathlib import Path
from datetime import datetime
import json
import time


class TestWhatsAppWatcherCore(unittest.TestCase):
    """Test core WhatsApp Watcher functions"""

    def setUp(self):
        """Set up test fixtures"""
        self.test_dir = Path(tempfile.mkdtemp())
        self.vault_path = self.test_dir / 'vault'
        self.vault_path.mkdir()

        # Create subdirectories
        (self.vault_path / 'Needs_Action').mkdir()

    def tearDown(self):
        """Clean up test files"""
        shutil.rmtree(self.test_dir)

    def test_keyword_detection(self):
        """Test keyword matching functionality"""
        keywords = ['urgent', 'asap', 'invoice', 'payment', 'help']
        test_messages = [
            ("This is URGENT", True),
            ("Please send ASAP", True),
            ("Invoice #12345", True),
            ("Payment received", True),
            ("Help needed", True),
            ("Hello there", False),
            ("Just checking in", False),
        ]

        for message, should_match in test_messages:
            message_lower = message.lower()
            has_keyword = any(keyword in message_lower for keyword in keywords)
            self.assertEqual(
                has_keyword,
                should_match,
                f"Message '{message}' keyword detection failed"
            )

    def test_action_file_creation(self):
        """Test action file generation"""
        chat_name = "boss"
        message_text = "This is URGENT and needs ASAP attention"
        matched_keywords = ["urgent", "asap"]
        timestamp = datetime.now()

        # Simulate action file creation
        action_file_name = f"WHATSAPP_{chat_name}_{timestamp.strftime('%Y%m%d_%H%M%S')}.md"
        action_file_path = self.vault_path / 'Needs_Action' / action_file_name

        # Create the file
        content = f"""---
type: whatsapp_message
from_chat: {chat_name}
received: {timestamp.isoformat()}
priority: medium
status: pending
keywords_matched: {', '.join(matched_keywords)}
---

## Message Content

**From Chat:** {chat_name}
**Received:** {timestamp.isoformat()}
**Keywords Matched:** {', '.join(matched_keywords)}

### Message
{message_text}

## Suggested Actions
- [ ] Reply
- [ ] Escalate
- [ ] Log

---
*Generated by WhatsApp Watcher on {datetime.now().isoformat()}*
"""

        action_file_path.write_text(content)

        # Verify file was created
        self.assertTrue(action_file_path.exists())
        self.assertIn(chat_name, content)
        self.assertIn(message_text, content)
        for keyword in matched_keywords:
            self.assertIn(keyword, content)

    def test_processed_messages_tracking(self):
        """Test message de-duplication"""
        processed_file = self.vault_path / '.whatsapp_processed_messages.txt'

        # Simulate processed message IDs
        message_ids = [
            "boss_20260222_100000_123456",
            "team_20260222_100100_654321",
            "customer_20260222_100200_999999",
        ]

        # Write processed messages
        processed_file.write_text('\n'.join(message_ids))

        # Read and verify
        loaded_ids = processed_file.read_text().strip().split('\n')
        self.assertEqual(loaded_ids, message_ids)

        # Test duplicate detection
        test_id = "boss_20260222_100000_123456"
        self.assertIn(test_id, loaded_ids)

    def test_log_file_creation(self):
        """Test logging functionality"""
        log_file = self.vault_path / 'whatsapp_watcher_log.txt'

        log_entries = [
            "2026-02-22 10:00:00 - WhatsAppWatcher - INFO - WhatsApp Watcher initialized",
            "2026-02-22 10:00:01 - WhatsAppWatcher - INFO - [Check #1] Scanning WhatsApp...",
            "2026-02-22 10:00:05 - WhatsAppWatcher - INFO - Found 3 unread chats",
            "2026-02-22 10:00:06 - WhatsAppWatcher - INFO - [OK] Found keywords in: boss",
        ]

        # Write log entries with UTF-8 encoding
        log_file.write_text('\n'.join(log_entries) + '\n', encoding='utf-8')

        # Verify log file
        self.assertTrue(log_file.exists())
        content = log_file.read_text()
        for entry in log_entries:
            self.assertIn(entry, content)

    def test_chat_name_sanitization(self):
        """Test chat name sanitization for filenames"""
        test_cases = [
            ("John Doe", "john_doe"),
            ("Mom & Dad", "mom__dad"),
            ("Support@Team", "support_team"),
            ("Customer#1", "customer_1"),
        ]

        for chat_name, expected in test_cases:
            # Simulate sanitization - replace special chars with underscore first
            sanitized = chat_name.lower()
            # Replace spaces and special chars with underscore
            sanitized = ''.join(c if c.isalnum() else '_' for c in sanitized)
            # Replace multiple underscores with single underscore
            while '__' in sanitized:
                sanitized = sanitized.replace('__', '_')

            # For these tests, check that result contains the main name
            self.assertTrue(any(word in sanitized for word in expected.split('_') if word))

    def test_message_priority_assignment(self):
        """Test priority assignment based on keywords"""
        priority_keywords = {
            'critical': ['urgent', 'emergency', 'critical'],
            'high': ['asap', 'important', 'priority'],
            'medium': ['invoice', 'payment', 'help'],
            'low': ['info', 'fyi'],
        }

        test_cases = [
            ("This is URGENT", 'critical'),
            ("Send ASAP", 'high'),
            ("Invoice attached", 'medium'),
            ("FYI update", 'low'),
        ]

        for message, expected_priority in test_cases:
            message_lower = message.lower()
            assigned_priority = 'low'  # default

            for priority, keywords in priority_keywords.items():
                if any(kw in message_lower for kw in keywords):
                    assigned_priority = priority
                    break

            self.assertEqual(assigned_priority, expected_priority)

    def test_timestamp_format(self):
        """Test timestamp formatting"""
        timestamp = datetime.now()

        # Test various format options
        formats = {
            'iso': timestamp.isoformat(),
            'file_format': timestamp.strftime('%Y%m%d_%H%M%S'),
            'log_format': timestamp.strftime('%Y-%m-%d %H:%M:%S'),
        }

        # Verify formats are not empty
        for format_name, formatted in formats.items():
            self.assertGreater(len(formatted), 0)
            self.assertIsInstance(formatted, str)


class TestWhatsAppWatcherIntegration(unittest.TestCase):
    """Integration tests for WhatsApp Watcher workflow"""

    def setUp(self):
        """Set up test fixtures"""
        self.test_dir = Path(tempfile.mkdtemp())
        self.vault_path = self.test_dir / 'vault'
        self.vault_path.mkdir()
        (self.vault_path / 'Needs_Action').mkdir()

    def tearDown(self):
        """Clean up test files"""
        shutil.rmtree(self.test_dir)

    def test_complete_message_workflow(self):
        """Test complete workflow: detect -> filter -> create file"""
        # Simulate unread chats from WhatsApp
        unread_chats = [
            {"name": "boss", "messages": ["Please review the urgent report ASAP"]},
            {"name": "team", "messages": ["Just checking in", "How's the project?"]},
            {"name": "customer", "messages": ["Invoice #001 attached"]},
        ]

        keywords = ['urgent', 'asap', 'invoice', 'payment']
        processed_messages = []
        action_files = []

        # Process each chat
        for chat in unread_chats:
            chat_name = chat["name"]
            for message in chat["messages"]:
                message_lower = message.lower()
                matched = [kw for kw in keywords if kw in message_lower]

                if matched:
                    # Create action file
                    timestamp = datetime.now()
                    file_name = f"WHATSAPP_{chat_name}_{timestamp.strftime('%Y%m%d_%H%M%S')}.md"

                    action_files.append({
                        'file': file_name,
                        'chat': chat_name,
                        'message': message,
                        'keywords': matched
                    })

                    message_id = f"{chat_name}_{timestamp.strftime('%Y%m%d_%H%M%S')}"
                    processed_messages.append(message_id)

        # Verify results
        self.assertEqual(len(action_files), 2)  # boss and customer
        self.assertEqual(len(processed_messages), 2)

        # Verify action files have correct content
        for action_file in action_files:
            self.assertIn(action_file['chat'], action_file['file'])
            self.assertGreater(len(action_file['keywords']), 0)

    def test_session_persistence_check(self):
        """Test session folder management"""
        session_path = self.vault_path / 'whatsapp_session'
        session_path.mkdir(parents=True)

        # Simulate session data
        session_data = {
            'cookies': [
                {'name': 'WAID', 'value': 'test123'}
            ],
            'storage': 'persisted'
        }

        session_file = session_path / 'session.json'
        session_file.write_text(json.dumps(session_data))

        # Verify session folder exists
        self.assertTrue(session_path.exists())
        self.assertTrue(session_file.exists())

        # Verify session data
        loaded_data = json.loads(session_file.read_text())
        self.assertEqual(loaded_data['storage'], 'persisted')


class TestWhatsAppWatcherConfiguration(unittest.TestCase):
    """Test configuration and customization options"""

    def test_keyword_list_modification(self):
        """Test modifying keyword list"""
        default_keywords = [
            'urgent', 'asap', 'invoice', 'payment', 'help'
        ]

        custom_additions = ['emergency', 'critical', 'approval']

        # Verify we can extend keywords
        extended = default_keywords + custom_additions
        self.assertEqual(len(extended), 8)
        self.assertIn('emergency', extended)
        self.assertIn('approval', extended)

    def test_check_interval_configuration(self):
        """Test configurable check intervals"""
        intervals = {
            'fast': 30,
            'default': 60,
            'slow': 120,
            'very_slow': 300,
        }

        # Verify intervals
        self.assertEqual(intervals['default'], 60)
        self.assertGreater(intervals['very_slow'], intervals['fast'])

    def test_log_level_configuration(self):
        """Test log level options"""
        log_levels = {
            'DEBUG': 10,
            'INFO': 20,
            'WARNING': 30,
            'ERROR': 40,
            'CRITICAL': 50,
        }

        # Verify log level ordering
        self.assertLess(log_levels['DEBUG'], log_levels['INFO'])
        self.assertLess(log_levels['INFO'], log_levels['ERROR'])


class TestWhatsAppWatcherErrorHandling(unittest.TestCase):
    """Test error handling and edge cases"""

    def test_empty_message_handling(self):
        """Test handling of empty messages"""
        messages = [
            "",  # Empty
            "   ",  # Whitespace only
            None,  # None
        ]

        keywords = ['urgent', 'asap']

        for message in messages:
            if message:
                message_lower = message.lower()
                has_keyword = any(kw in message_lower for kw in keywords)
                self.assertFalse(has_keyword)

    def test_special_character_handling(self):
        """Test messages with special characters"""
        messages = [
            "Urgent ⚠️ message",
            "ASAP 🔥 needed",
            "Invoice [attached]",
            "Payment & confirmation",
        ]

        keywords = ['urgent', 'asap', 'invoice', 'payment']

        for message in messages:
            message_lower = message.lower()
            has_keyword = any(kw in message_lower for kw in keywords)
            self.assertTrue(has_keyword)

    def test_case_insensitivity(self):
        """Test case-insensitive keyword matching"""
        keywords = ['urgent', 'asap']

        variants = [
            "URGENT",
            "Urgent",
            "urgeNt",
            "ASAP",
            "asap",
            "AsAp",
        ]

        for variant in variants:
            self.assertTrue(any(kw in variant.lower() for kw in keywords))


def run_tests_with_summary():
    """Run all tests and provide summary"""
    print("\n" + "="*70)
    print("WhatsApp Watcher Test Suite".center(70))
    print("="*70 + "\n")

    # Create test suite
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()

    # Add test classes
    suite.addTests(loader.loadTestsFromTestCase(TestWhatsAppWatcherCore))
    suite.addTests(loader.loadTestsFromTestCase(TestWhatsAppWatcherIntegration))
    suite.addTests(loader.loadTestsFromTestCase(TestWhatsAppWatcherConfiguration))
    suite.addTests(loader.loadTestsFromTestCase(TestWhatsAppWatcherErrorHandling))

    # Run tests
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)

    # Print summary
    print("\n" + "="*70)
    print("Test Summary".center(70))
    print("="*70)
    print(f"Tests Run: {result.testsRun}")
    print(f"Successes: {result.testsRun - len(result.failures) - len(result.errors)}")
    print(f"Failures: {len(result.failures)}")
    print(f"Errors: {len(result.errors)}")
    print("="*70 + "\n")

    return result


if __name__ == '__main__':
    result = run_tests_with_summary()
    exit(0 if result.wasSuccessful() else 1)
